<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; color: #1e293b; font-size: 13px; padding: 40px; }
        .header { text-align: center; margin-bottom: 32px; border-bottom: 2px solid #2563eb; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #2563eb; letter-spacing: -0.5px; }
        .logo span { color: #1e293b; }
        .title { font-size: 13px; color: #64748b; margin-top: 4px; }
        .ref-box { background: #eff6ff; border: 1.5px solid #bfdbfe; border-radius: 10px; padding: 18px 24px; text-align: center; margin-bottom: 28px; }
        .ref-label { font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 2px; margin-bottom: 6px; }
        .ref-number { font-size: 32px; font-weight: bold; color: #2563eb; letter-spacing: 6px; }
        .section-title { font-size: 10px; font-weight: bold; color: #64748b; text-transform: uppercase; letter-spacing: 1.5px; margin-bottom: 10px; }
        .detail-table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
        .detail-table td { padding: 10px 14px; font-size: 13px; }
        .detail-table tr:nth-child(odd) td { background: #f8fafc; }
        .detail-table tr:nth-child(even) td { background: #ffffff; }
        .detail-table td:first-child { color: #64748b; width: 40%; }
        .detail-table td:last-child { font-weight: 600; color: #1e293b; }
        .route-box { background: #1e293b; color: white; border-radius: 10px; padding: 16px 20px; margin-bottom: 24px; display: flex; justify-content: space-between; align-items: center; }
        .route-from { font-size: 18px; font-weight: bold; }
        .route-arrow { font-size: 18px; color: #94a3b8; }
        .route-to { font-size: 18px; font-weight: bold; }
        .route-time { font-size: 11px; color: #94a3b8; margin-top: 3px; }
        .status-badge { display: inline-block; background: #dcfce7; color: #166534; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; text-align: center; color: #94a3b8; font-size: 11px; }
        .payment-badge { display: inline-block; background: #fef3c7; color: #92400e; padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">Bus<span>Book</span></div>
        <div class="title">Booking Receipt</div>
    </div>

    <div class="ref-box">
        <div class="ref-label">Booking Reference</div>
        <div class="ref-number">{{ $booking->booking_reference }}</div>
    </div>

    <div class="route-box">
        <div>
            <div class="route-from">{{ $booking->busRoute->from_location }}</div>
            <div class="route-time">{{ \Carbon\Carbon::parse($booking->busRoute->departure_time)->format('g:i A') }}</div>
        </div>
        <div class="route-arrow">→</div>
        <div style="text-align:right">
            <div class="route-to">{{ $booking->busRoute->to_location }}</div>
            <div class="route-time">{{ \Carbon\Carbon::parse($booking->busRoute->arrival_time)->format('g:i A') }}</div>
        </div>
    </div>

    <p class="section-title">Booking details</p>
    <table class="detail-table">
        <tr><td>Travel date</td><td>{{ $booking->travel_date->format('l, d F Y') }}</td></tr>
        <tr><td>Bus number</td><td style="font-family:monospace;font-weight:bold">{{ $booking->busRoute->bus_number ?? '—' }}</td></tr>
        <tr><td>{{ $booking->seats->count() > 1 ? 'Seats' : 'Seat' }}</td><td>{{ $booking->seats->pluck('seat_number')->join(', ') }}</td></tr>
        <tr><td>Total price</td><td>LKR {{ number_format($booking->busRoute->price * $booking->seats->count()) }}</td></tr>
        <tr><td>Status</td><td><span class="status-badge">{{ ucfirst($booking->status) }}</span></td></tr>
        <tr><td>Payment</td><td><span class="payment-badge">{{ $booking->payment_method === 'station' ? 'Pay at station' : 'Online' }}</span></td></tr>
        <tr><td>Price</td><td>LKR {{ number_format($booking->busRoute->price) }}</td></tr>
    </table>

    <p class="section-title">Passenger details</p>
    <table class="detail-table">
        <tr><td>Full name</td><td>{{ $booking->passenger_name }}</td></tr>
        <tr><td>Gender</td><td>{{ ucfirst($booking->gender) }}</td></tr>
        <tr><td>NIC</td><td>{{ $booking->nic }}</td></tr>
        <tr><td>Email</td><td>{{ $booking->email ?? '—' }}</td></tr>
    </table>

    <div class="footer">
        <p>Generated by BusBook · {{ now()->format('d M Y, g:i A') }}</p>
        <p style="margin-top:4px">Keep this reference safe: <strong>{{ $booking->booking_reference }}</strong></p>
    </div>
</body>
</html>